### ISSUE TITLE
Background image.

### ISSUE THREAD

**Issue by inf13** [andyhutch77/MvcRazorToPdf#23]
I trying to add a background image for every pdf page. Is it possible?
(for example html analogue: body style="background: url(logo.jpg)" )

**Comment by andyhutch77** [comment]
@inf13 How did you get on with this? Any luck?

**Comment by germanger** [comment]
are simple images (not background images) admitted?, eg: `<img src="..." />`

Using the XMLWorker demo didn't work:
http://demo.itextsupport.com/xmlworker/

HTML Code:
`<img src="http://static1.squarespace.com/static/532abed3e4b025f227941d11/t/532ce5e3e4b0f59c2979d8c2/1395451365611/" alt="" />`

(just a random image)

**Comment by germanger** [comment]
Ah, to answer myself.. they are admitted but with a local path (eg: "C:\foo.png", which is what `Server.MapPath` returns). URLs are not admitted nor relative paths...

It would be nice that Base64 was admitted though, because between a local absolute path and a base64 image, `<img src="data:....." />`, I think the second is more elegant

**Comment by andyhutch77** [comment]
@germanger Base64 would be good, if you add it I can include it. :+1:
